
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTBYID_SUCCESS = "FETCH_PRODUCTBYID_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
export const  INCREASE = "INCREASE";
export const DECREASE = "DECREASE";
export const REMOVE = "REMOVE";
export const GET_TOTALS = "GET_TOTALS";
export const TOGGLE_AMOUNT = "TOGGLE_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";
 export const ADD_TO_CART="ADD_TO_CART";